// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ATable: typeof import('ant-design-vue/es')['Table']
    ATree: typeof import('ant-design-vue/es')['Tree']
    MenuItem: typeof import('./src/components/MenuItem/index.vue')['default']
    MyBreadcrumb: typeof import('./src/components/MyBreadcrumb/index.vue')['default']
    MyHeader: typeof import('./src/components/MyHeader/index.vue')['default']
    MyRouteTag: typeof import('./src/components/MyRouteTag/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
  }
}
